### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by kenjibizweb** [asanka-x/Phonegap-SMS#2] opened 2014-02-09 08:54 UTC
Hi, i have been trying to implement this plugin into Phonegap but keep on getting this error as Class Not Found. It would be great if you can have some samples on initializing this plugin. Thank you and appreciate it.

**Comment by andwaw** [comment] 2014-02-17 23:51
Hi, I have the same issue. When I use the isSupported function, both callbacks are fired.

**Comment by ideepakrnd** [comment] 2014-02-26 11:45
Hi, I am unable to implement SMSPlugin. Please help me out..

I have add plugin to cordova project using below code...
cordova plugin add https://github.com/asanka-x/Phonegap-SMS.git

But i am getting below error:-

![capture](https://f.cloud.github.com/assets/5327457/2269538/6ce786d4-9edb-11e3-9602-0942a886cfde.PNG)

**Comment by ibcomputing** [comment] 2014-03-04 17:00
The Class Not Found error is caused by a bug in the plugin.xml code. Line 18 should read < feature name="SmsPlugin" > as the plugin name is case sensitive and currently does not match the name referenced in the JavaScript file.
Please can this be fixed ASAP as I need to use the plugin via PhoneGap Build and can't until this bug is fixed. Happy to donate towards the project if that helps!

**Comment by asanka-x** [comment] 2014-09-23 04:17
Fix merged

**Closed as completed** 2014-09-23 04:17 UTC
